name: "gxpd dbt action"
description: "Run and schedule dbt commands directly in your Github repo"
author: "Yupei Chen"

inputs:
  dbt_command:
    description: "dbt command"
    default: "dbt --log-format text debug --profiles-dir ."
    required: true
  dbt_project_folder:
    description: "dbt project folder. Defaults to ."
    default: "."
    required: false
outputs:
  result:
    description: "Success or failure of the dbt command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dbt_command }}
branding:
  icon: 'database'
  color: 'orange'